# Generated by Django 4.0.4 on 2022-05-25 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'Коллекция', 'verbose_name_plural': 'Коллекции'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='door',
            options={'verbose_name': 'Дверь', 'verbose_name_plural': 'Двери'},
        ),
        migrations.AlterField(
            model_name='collection',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test1', to='doors.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Название коллекции'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='door',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test2', to='doors.collection', verbose_name='Коллекция'),
        ),
        migrations.AlterField(
            model_name='door',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название модели'),
        ),
    ]
