# Generated by Django 4.0.4 on 2022-05-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doors', '0003_remove_door_name_door_canvas_door_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='name',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Название'),
        ),
    ]
